import PDFDocument from "pdfkit";

import { prisma } from "../lib/prisma.js";

import { applyPdfUnicodeFont } from "./pdfKitUnicodeFont.js";
import { MEDICAL_CONDITION_CODES } from "../validation/medicalHistory.schemas.js";

/* -------------------------------------------------------------------------- */
/* Ortak yardımcılar                                                          */
/* -------------------------------------------------------------------------- */

type Doc = PDFKit.PDFDocument;

interface ClinicHeaderData {
  name: string;
  address: string | null;
  city: string | null;
  phone: string | null;
}

async function fetchClinicHeader(clinicId: string): Promise<ClinicHeaderData> {
  const c = await prisma.clinic.findUnique({
    where: { id: clinicId },
    select: { name: true, address: true, city: true, phone: true },
  });
  return {
    name: c?.name ?? "DentEase PH",
    address: c?.address ?? null,
    city: c?.city ?? null,
    phone: c?.phone ?? null,
  };
}

function formatDate(d: Date | null | undefined): string {
  if (!d) return "—";
  return new Date(d).toLocaleDateString("en-PH", {
    timeZone: "Asia/Manila",
    year: "numeric",
    month: "short",
    day: "2-digit",
  });
}

function formatDateTime(d: Date | null | undefined): string {
  if (!d) return "—";
  return new Date(d).toLocaleString("en-PH", {
    timeZone: "Asia/Manila",
  });
}

function money(v: string | number | null | undefined): string {
  if (v === null || v === undefined || v === "") return "₱ 0.00";
  const num = typeof v === "string" ? Number(v) : v;
  return `₱ ${num.toLocaleString("en-PH", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
}

function ageFromBirthDate(d: Date | null | undefined): string {
  if (!d) return "—";
  const now = new Date();
  const birth = new Date(d);
  let age = now.getFullYear() - birth.getFullYear();
  const mDiff = now.getMonth() - birth.getMonth();
  if (mDiff < 0 || (mDiff === 0 && now.getDate() < birth.getDate())) age--;
  return String(age);
}

function yesNo(v: boolean | null | undefined): string {
  if (v === true) return "Yes";
  if (v === false) return "No";
  return "—";
}

function drawHeader(doc: Doc, clinic: ClinicHeaderData, title: string): void {
  doc.fillColor("#0f172a").fontSize(18).text(clinic.name, 48, 48);
  doc
    .fillColor("#64748b")
    .fontSize(9)
    .text([clinic.address, clinic.city].filter(Boolean).join(", "), 48, 72);
  if (clinic.phone) doc.text(`Tel: ${clinic.phone}`, 48, 84);

  doc
    .fillColor("#10b981")
    .fontSize(13)
    .text(title, 48, 106, { align: "right", width: 499 });

  doc
    .strokeColor("#10b981")
    .lineWidth(2)
    .moveTo(48, 128)
    .lineTo(547, 128)
    .stroke();

  doc.y = 140;
  doc.x = 48;
}

function drawFooter(doc: Doc, note?: string): void {
  const m = doc.page.margins;
  const bottomY = doc.page.height - m.bottom;
  doc
    .strokeColor("#cbd5e1")
    .lineWidth(0.5)
    .moveTo(48, bottomY - 14)
    .lineTo(547, bottomY - 14)
    .stroke();
  doc
    .fontSize(8)
    .fillColor("#94a3b8")
    .text(
      note ?? "Generated by DentEase PH — Internal clinic record.",
      48,
      bottomY - 10,
      { align: "center", width: 499 },
    );
}

function sectionTitle(doc: Doc, title: string): void {
  if (doc.y > 740) doc.addPage();
  doc.moveDown(0.6);
  doc
    .fillColor("#0f172a")
    .fontSize(12)
    .text(title, { underline: false });
  doc
    .strokeColor("#10b981")
    .lineWidth(1)
    .moveTo(doc.x, doc.y + 1)
    .lineTo(doc.x + 499, doc.y + 1)
    .stroke();
  doc.moveDown(0.3);
  doc.fillColor("#0f172a").fontSize(10);
}

/**
 * Basit iki-sütunlu "label: value" grid.
 * rows: her eleman [label, value]
 */
function twoColGrid(doc: Doc, rows: Array<[string, string]>): void {
  const colW = 247;
  const rowH = 16;
  const startX = doc.x;
  let y = doc.y;
  for (let i = 0; i < rows.length; i += 2) {
    if (y > 770) {
      doc.addPage();
      y = doc.y;
    }
    const left = rows[i];
    const right = rows[i + 1];
    doc.fontSize(9).fillColor("#64748b").text(left[0], startX, y);
    doc.fontSize(10).fillColor("#0f172a").text(left[1] || "—", startX, y + 10, { width: colW - 10 });
    if (right) {
      doc.fontSize(9).fillColor("#64748b").text(right[0], startX + colW, y);
      doc
        .fontSize(10)
        .fillColor("#0f172a")
        .text(right[1] || "—", startX + colW, y + 10, { width: colW - 10 });
    }
    y += rowH + 10;
  }
  doc.y = y + 4;
  doc.x = startX;
}

function signatureBlock(doc: Doc, labelLeft: string, labelRight: string): void {
  if (doc.y > 700) doc.addPage();
  doc.moveDown(2);
  const y = doc.y;
  doc.strokeColor("#0f172a").lineWidth(0.7);
  doc.moveTo(48, y).lineTo(280, y).stroke();
  doc.moveTo(320, y).lineTo(547, y).stroke();
  doc.fillColor("#475569").fontSize(9);
  doc.text(labelLeft, 48, y + 4, { width: 232, align: "center" });
  doc.text(labelRight, 320, y + 4, { width: 227, align: "center" });
  doc.moveDown(2);
  doc.x = 48;
}

function buildDoc(): { doc: Doc; chunks: Buffer[]; promise: Promise<Buffer> } {
  const doc = new PDFDocument({ size: "A4", margin: 48, bufferPages: true });
  applyPdfUnicodeFont(doc);
  const chunks: Buffer[] = [];
  doc.on("data", (c: Buffer) => chunks.push(c));
  const promise = new Promise<Buffer>((resolve, reject) => {
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);
  });
  return { doc, chunks, promise };
}

async function loadPatientFull(clinicId: string, patientId: string) {
  const patient = await prisma.patient.findFirst({
    where: { id: patientId, clinicId },
    include: {
      teeth: { orderBy: { toothNumber: "asc" } },
      medicalRecord: {
        include: { recordedBy: { select: { firstName: true, lastName: true } } },
      },
      appointments: {
        orderBy: { scheduledAt: "desc" },
        take: 10,
        include: { dentist: { select: { firstName: true, lastName: true } } },
      },
      invoices: {
        orderBy: { createdAt: "desc" },
        take: 50,
        include: {
          payments: true,
          appointment: {
            include: {
              treatments: {
                include: { dentist: { select: { firstName: true, lastName: true } } },
              },
            },
          },
        },
      },
    },
  });
  if (!patient) {
    throw new Error("Patient not found");
  }
  return patient;
}

/* -------------------------------------------------------------------------- */
/* PDF 1 — Dental Record (patient demografi + diş durumu + son tedaviler)     */
/* -------------------------------------------------------------------------- */

export async function generateDentalRecordPdf(
  clinicId: string,
  patientId: string,
): Promise<Buffer> {
  const clinic = await fetchClinicHeader(clinicId);
  const p = await loadPatientFull(clinicId, patientId);

  const { doc, promise } = buildDoc();
  drawHeader(doc, clinic, "Dental Record");

  sectionTitle(doc, "Patient information");
  const fullName = [p.firstName, p.middleName, p.lastName].filter(Boolean).join(" ");
  twoColGrid(doc, [
    ["Full name", fullName],
    ["Nickname", p.nickname ?? ""],
    ["Date of birth", formatDate(p.birthDate)],
    ["Age", ageFromBirthDate(p.birthDate)],
    ["Gender", p.gender ?? ""],
    ["Civil status", p.civilStatus ?? ""],
    ["Phone", p.phone],
    ["Email", p.email ?? ""],
    ["Occupation", p.occupation ?? ""],
    ["Nationality", p.nationality ?? ""],
    ["Religion", p.religion ?? ""],
    ["PhilHealth #", p.philhealthNo ?? ""],
    ["Address", [p.address, p.city, p.province].filter(Boolean).join(", ")],
    ["Emergency contact", [p.emergencyContactName, p.emergencyContactPhone].filter(Boolean).join(" · ")],
    ["Referred by", p.referralSource ?? ""],
    ["Previous dentist", p.previousDentist ?? ""],
    ["Last dental visit", formatDate(p.lastDentalVisit)],
    ["Reason for visit", p.reasonForVisit ?? ""],
  ]);

  sectionTitle(doc, "Vital signs & allergies");
  const bp =
    p.bloodPressureSystolic && p.bloodPressureDiastolic
      ? `${p.bloodPressureSystolic}/${p.bloodPressureDiastolic} mmHg`
      : "";
  twoColGrid(doc, [
    ["Blood pressure", bp],
    ["Pulse rate", p.pulseRate ? `${p.pulseRate} bpm` : ""],
    ["Blood type", p.bloodType ?? ""],
    ["Known allergies", (p.allergies ?? []).join(", ")],
  ]);

  // Diş durumu — tabelka: sadece default dışındaki dişler
  sectionTitle(doc, "Tooth conditions");
  const nonDefault = p.teeth.filter((t) => t.condition !== "HEALTHY" || (t.notes && t.notes.trim().length));
  if (nonDefault.length === 0) {
    doc.fontSize(10).fillColor("#64748b").text("No recorded tooth conditions.");
  } else {
    doc.fontSize(10).fillColor("#0f172a");
    const colX = { n: 48, c: 110, s: 280, u: 420 };
    const toothHdrY = doc.y;
    doc.fillColor("#64748b").fontSize(9);
    doc.text("TOOTH", colX.n, toothHdrY);
    doc.text("CONDITION", colX.c, toothHdrY);
    doc.text("SURFACES", colX.s, toothHdrY);
    doc.text("UPDATED", colX.u, toothHdrY);
    doc
      .strokeColor("#cbd5e1")
      .moveTo(48, toothHdrY + 12)
      .lineTo(547, toothHdrY + 12)
      .stroke();
    doc.y = toothHdrY + 16;
    for (const t of nonDefault) {
      if (doc.y > 770) doc.addPage();
      const y = doc.y;
      doc.fillColor("#0f172a").fontSize(10);
      doc.text(String(t.toothNumber), colX.n, y, { width: 50 });
      doc.text(t.condition.replace(/_/g, " "), colX.c, y, { width: 160 });
      doc.text((t.surfaces ?? []).join(", ") || "—", colX.s, y, { width: 130 });
      doc.text(formatDate(t.updatedAt), colX.u, y, { width: 120 });
      doc.moveDown(0.4);
    }
  }

  // Son randevular
  sectionTitle(doc, "Recent appointments");
  if (p.appointments.length === 0) {
    doc.fontSize(10).fillColor("#64748b").text("No past appointments.");
  } else {
    for (const a of p.appointments.slice(0, 8)) {
      if (doc.y > 770) doc.addPage();
      doc
        .fontSize(10)
        .fillColor("#0f172a")
        .text(
          `• ${formatDateTime(a.scheduledAt)} — ${(a.type ?? "—").replace(/_/g, " ")} — Dr. ${a.dentist.firstName} ${a.dentist.lastName} — ${a.status}`,
        );
    }
  }

  drawFooter(doc);
  doc.end();
  return promise;
}

/* -------------------------------------------------------------------------- */
/* PDF 2 — Medical History Questionnaire                                      */
/* -------------------------------------------------------------------------- */

const CONDITION_LABEL: Record<(typeof MEDICAL_CONDITION_CODES)[number], string> = {
  HEART_DISEASE: "Heart disease",
  CONGENITAL_HEART: "Congenital heart disorder",
  RHEUMATIC_FEVER: "Rheumatic fever",
  ANGINA: "Angina",
  HBP: "High blood pressure",
  LBP: "Low blood pressure",
  DIABETES: "Diabetes",
  ASTHMA: "Asthma",
  TB: "Tuberculosis",
  BRONCHITIS: "Bronchitis",
  EMPHYSEMA: "Emphysema",
  SINUSITIS: "Sinusitis",
  HAY_FEVER: "Hay fever",
  KIDNEY: "Kidney disease",
  LIVER_HEPATITIS: "Liver / Hepatitis",
  JAUNDICE: "Jaundice",
  ULCERS: "Stomach ulcers",
  THYROID: "Thyroid problem",
  EPILEPSY: "Epilepsy",
  FAINTING: "Fainting spells",
  STROKE: "Stroke",
  ANEMIA: "Anemia",
  HEMOPHILIA: "Hemophilia / Bleeding disorder",
  HIV_AIDS: "HIV / AIDS",
  CANCER: "Cancer / Tumor",
  ARTHRITIS: "Arthritis / Rheumatism",
  PSYCHIATRIC: "Psychiatric condition",
  VENEREAL: "Venereal disease / STD",
};

export async function generateMedicalHistoryPdf(
  clinicId: string,
  patientId: string,
): Promise<Buffer> {
  const clinic = await fetchClinicHeader(clinicId);
  const p = await loadPatientFull(clinicId, patientId);
  const m = p.medicalRecord;

  const { doc, promise } = buildDoc();
  drawHeader(doc, clinic, "Medical History Questionnaire");

  sectionTitle(doc, "Patient");
  const fullName = [p.firstName, p.middleName, p.lastName].filter(Boolean).join(" ");
  twoColGrid(doc, [
    ["Full name", fullName],
    ["Date of birth", formatDate(p.birthDate)],
    ["Age", ageFromBirthDate(p.birthDate)],
    ["Gender", p.gender ?? ""],
    ["Phone", p.phone],
    [
      "Recorded by",
      m?.recordedBy ? `Dr. ${m.recordedBy.firstName} ${m.recordedBy.lastName}` : "—",
    ],
    ["Recorded at", m?.recordedAt ? formatDateTime(m.recordedAt) : ""],
    ["Version", m?.version ? `v${m.version}` : ""],
  ]);

  sectionTitle(doc, "General health");
  twoColGrid(doc, [
    ["Currently under physician care?", yesNo(m?.underPhysicianCare)],
    ["Reason", m?.underPhysicianCareReason ?? ""],
    ["Ever hospitalized?", yesNo(m?.hospitalized)],
    [
      "Hospitalization details",
      [m?.hospitalizedYear ? String(m.hospitalizedYear) : null, m?.hospitalizedReason ?? null]
        .filter(Boolean)
        .join(" — "),
    ],
    ["Taking medications?", yesNo(m?.takingMedications)],
    ["Medications", m?.medicationsList ?? ""],
    ["Serious illness / surgery?", yesNo(m?.seriousIllness)],
    ["Details", m?.seriousIllnessDetails ?? ""],
  ]);

  // 28 koşul — kontrol listesi
  sectionTitle(doc, "Medical conditions");
  const conditions = new Set<string>(m?.conditions ?? []);
  const listColWidth = 249;
  const itemH = 14;
  let y = doc.y;
  const startY = y;
  const codes = MEDICAL_CONDITION_CODES;
  for (let i = 0; i < codes.length; i++) {
    const code = codes[i];
    const col = i % 2;
    const row = Math.floor(i / 2);
    const x = 48 + col * listColWidth;
    const cy = startY + row * itemH;
    if (cy > 760) continue;
    doc.strokeColor("#0f172a").lineWidth(0.7).rect(x, cy, 8, 8).stroke();
    if (conditions.has(code)) {
      doc
        .save()
        .strokeColor("#10b981")
        .lineWidth(1.2)
        .moveTo(x + 1, cy + 4)
        .lineTo(x + 3, cy + 6)
        .lineTo(x + 7, cy + 1)
        .stroke()
        .restore();
    }
    doc.fillColor("#0f172a").fontSize(9).text(CONDITION_LABEL[code], x + 12, cy - 1, {
      width: listColWidth - 20,
    });
  }
  const rows = Math.ceil(codes.length / 2);
  doc.y = startY + rows * itemH + 8;

  if (m?.conditionsOther) {
    doc.fontSize(9).fillColor("#64748b").text("Other / notes", 48, doc.y);
    doc.fontSize(10).fillColor("#0f172a").text(m.conditionsOther, 48, doc.y + 10, { width: 499 });
    doc.moveDown(1);
  }

  sectionTitle(doc, "Allergies");
  twoColGrid(doc, [
    ["Local anesthetic", yesNo(m?.allergyAnesthetic)],
    ["Penicillin", yesNo(m?.allergyPenicillin)],
    ["Sulfa drugs", yesNo(m?.allergySulfa)],
    ["Aspirin", yesNo(m?.allergyAspirin)],
    ["Latex / Rubber", yesNo(m?.allergyLatex)],
    ["Other", m?.allergyOther ?? ""],
  ]);

  sectionTitle(doc, "Lifestyle");
  twoColGrid(doc, [
    ["Smoking", m?.smoker ?? ""],
    ["Alcohol", m?.alcohol ?? ""],
    ["Recreational drug use", m?.recreationalDrug ?? ""],
  ]);

  if (p.gender === "FEMALE") {
    sectionTitle(doc, "Female-specific");
    twoColGrid(doc, [
      ["Pregnant?", yesNo(m?.isPregnant)],
      ["Pregnancy month", m?.pregnancyMonths ? String(m.pregnancyMonths) : ""],
      ["Breastfeeding?", yesNo(m?.isBreastfeeding)],
      ["Using contraceptives?", yesNo(m?.usesContraceptive)],
    ]);
  }

  if (m?.notes) {
    sectionTitle(doc, "Additional notes");
    doc.fontSize(10).fillColor("#0f172a").text(m.notes, { width: 499 });
  }

  signatureBlock(doc, "Patient / Guardian signature", "Dentist signature");
  drawFooter(doc);
  doc.end();
  return promise;
}

/* -------------------------------------------------------------------------- */
/* PDF 3 — Treatment Record (tedavi geçmişi + bakiye)                         */
/* -------------------------------------------------------------------------- */

export async function generateTreatmentRecordPdf(
  clinicId: string,
  patientId: string,
): Promise<Buffer> {
  const clinic = await fetchClinicHeader(clinicId);
  const p = await loadPatientFull(clinicId, patientId);

  const { doc, promise } = buildDoc();
  drawHeader(doc, clinic, "Treatment Record");

  sectionTitle(doc, "Patient");
  const fullName = [p.firstName, p.middleName, p.lastName].filter(Boolean).join(" ");
  twoColGrid(doc, [
    ["Full name", fullName],
    ["Date of birth", formatDate(p.birthDate)],
    ["Phone", p.phone],
    ["PhilHealth #", p.philhealthNo ?? ""],
  ]);

  // Tüm tedavileri doğrudan Treatment tablosundan çek
  const treatments = await prisma.treatment.findMany({
    where: { patientId },
    orderBy: { createdAt: "asc" },
    include: { dentist: { select: { firstName: true, lastName: true } } },
  });

  type Row = {
    date: Date;
    dentist: string;
    procedure: string;
    teeth: string;
    qty: number;
    unit: string;
    total: string;
  };
  const rows: Row[] = treatments.map((t) => ({
    date: t.createdAt,
    dentist: `Dr. ${t.dentist.firstName} ${t.dentist.lastName}`,
    procedure: t.procedure.replace(/_/g, " "),
    teeth: (t.toothIds ?? []).join(", ") || "—",
    qty: t.quantity,
    unit: t.unitPrice.toString(),
    total: (Number(t.unitPrice) * t.quantity).toFixed(2),
  }));

  let totalBilled = 0;
  let totalPaid = 0;
  for (const inv of p.invoices) {
    totalBilled += Number(inv.total);
    for (const pay of inv.payments) totalPaid += Number(pay.amount);
  }

  sectionTitle(doc, "Treatments performed");
  if (rows.length === 0) {
    doc.fontSize(10).fillColor("#64748b").text("No treatments recorded yet.");
  } else {
    const col = { date: 48, proc: 120, tooth: 245, qty: 300, unit: 340, total: 410, dent: 475 };
    const tHdrY = doc.y;
    doc.fontSize(9).fillColor("#64748b");
    doc.text("DATE", col.date, tHdrY);
    doc.text("PROCEDURE", col.proc, tHdrY);
    doc.text("TOOTH", col.tooth, tHdrY);
    doc.text("QTY", col.qty, tHdrY);
    doc.text("UNIT", col.unit, tHdrY);
    doc.text("TOTAL", col.total, tHdrY);
    doc.text("DENTIST", col.dent, tHdrY);
    doc
      .strokeColor("#cbd5e1")
      .moveTo(48, tHdrY + 12)
      .lineTo(547, tHdrY + 12)
      .stroke();
    doc.y = tHdrY + 16;

    for (const r of rows) {
      if (doc.y > 770) doc.addPage();
      const rowTop = doc.y;
      const sx = doc.x;
      const sy = doc.y;
      doc.x = col.proc;
      doc.y = rowTop;
      const procH = doc.heightOfString(r.procedure, { width: 120 });
      doc.x = sx;
      doc.y = sy;
      doc.fontSize(9).fillColor("#0f172a");
      doc.text(formatDate(r.date), col.date, rowTop, { width: 70 });
      doc.text(r.procedure, col.proc, rowTop, { width: 120 });
      doc.text(r.teeth, col.tooth, rowTop, { width: 50 });
      doc.text(String(r.qty), col.qty, rowTop, { width: 35 });
      doc.text(money(r.unit), col.unit, rowTop, { width: 65 });
      doc.text(money(r.total), col.total, rowTop, { width: 60 });
      doc.text(r.dentist, col.dent, rowTop, { width: 72 });
      doc.y = rowTop + Math.max(procH, 11) + 6;
    }
  }

  sectionTitle(doc, "Financial summary");
  const paidInvoices = p.invoices.filter((i) => i.status === "PAID").length;
  const partialInvoices = p.invoices.filter((i) => i.status === "PARTIAL").length;
  const unpaidInvoices = p.invoices.filter((i) => i.status === "UNPAID").length;
  twoColGrid(doc, [
    ["Total billed", money(totalBilled)],
    ["Total paid", money(totalPaid)],
    ["Outstanding balance", money(totalBilled - totalPaid)],
    ["Invoices count", String(p.invoices.length)],
    ["Paid invoices", String(paidInvoices)],
    ["Partially paid invoices", String(partialInvoices)],
    ["Unpaid invoices", String(unpaidInvoices)],
    ["Last payment date", formatDate(p.invoices.flatMap((i) => i.payments).sort((a, b) => b.paidAt.getTime() - a.paidAt.getTime())[0]?.paidAt)],
  ]);

  drawFooter(doc);
  doc.end();
  return promise;
}

/* -------------------------------------------------------------------------- */
/* PDF 4 — Informed Consent (tam metin + imza alanı)                          */
/* -------------------------------------------------------------------------- */

const CONSENT_TEXT = [
  "1. I authorize Dr. ______________________ and associates of the clinic mentioned above to perform upon me (or the patient named above) any dental treatment deemed necessary, including diagnostic procedures, preventive dentistry, restorative, endodontic, periodontal, surgical, prosthetic and orthodontic procedures.",
  "2. I understand that every dental procedure has associated risks. Potential risks include but are not limited to pain, swelling, bruising, infection, allergic reactions, nerve injury, prolonged numbness, temporary or permanent sensitivity, jaw-joint discomfort, breakage of instruments, and the possibility of adverse reactions to local anesthetics or medications.",
  "3. I acknowledge that the practice of dentistry is not an exact science and that no guarantees have been made regarding the outcome of any treatment. The dentist has explained to me alternative treatments where applicable.",
  "4. I consent to the use of photographs, x-rays, or other diagnostic aids for the purpose of diagnosis, treatment planning, and patient education, with my identifying information removed if used in presentations or publications.",
  "5. I agree to disclose and update my complete medical history, including all medications I am taking and any allergies I have. I understand that failure to do so may adversely affect my treatment.",
  "6. I have read and understand the fees associated with the proposed treatment and agree to pay for all services rendered. I understand the clinic's cancellation and rescheduling policies.",
  "7. I consent to the collection, storage, and processing of my personal and health information in accordance with the Data Privacy Act of 2012 (RA 10173) for the purposes of providing dental care, communicating with me, and complying with applicable laws.",
  "8. I have been given the opportunity to ask questions and have received satisfactory answers. I am signing this consent freely and voluntarily.",
];

const CONSENT_ACK_LINES = [
  "Identity and treatment plan verified with the patient / guardian",
  "Allergy and medication risks were discussed",
  "Post-procedure instructions were explained",
  "Estimated total fee and payment terms were explained",
  "Data Privacy consent and communication channels were confirmed",
];

export async function generateInformedConsentPdf(
  clinicId: string,
  patientId: string,
): Promise<Buffer> {
  const clinic = await fetchClinicHeader(clinicId);
  const p = await loadPatientFull(clinicId, patientId);

  const { doc, promise } = buildDoc();
  drawHeader(doc, clinic, "Informed Consent");

  sectionTitle(doc, "Patient");
  const fullName = [p.firstName, p.middleName, p.lastName].filter(Boolean).join(" ");
  const latestAppt = p.appointments[0];
  const latestTreatments = latestAppt
    ? p.invoices
        .filter((i) => i.appointmentId === latestAppt.id)
        .flatMap((i) => i.appointment?.treatments ?? [])
    : [];
  const latestSummary =
    latestTreatments.length > 0
      ? latestTreatments
          .slice(0, 3)
          .map((t) => t.procedure.replace(/_/g, " "))
          .join(", ")
      : "General dental care";
  twoColGrid(doc, [
    ["Full name", fullName],
    ["Date of birth", formatDate(p.birthDate)],
    ["Age", ageFromBirthDate(p.birthDate)],
    ["Phone", p.phone],
    ["Recent visit", latestAppt ? formatDateTime(latestAppt.scheduledAt) : "—"],
    ["Planned / discussed treatment", latestSummary],
  ]);

  sectionTitle(doc, "Consent");
  doc.fontSize(10).fillColor("#0f172a");
  for (const para of CONSENT_TEXT) {
    if (doc.y > 720) doc.addPage();
    doc.text(para, { width: 499, align: "justify" });
    doc.moveDown(0.3);
  }

  sectionTitle(doc, "Chairside checklist (to be completed before signature)");
  for (const line of CONSENT_ACK_LINES) {
    if (doc.y > 770) doc.addPage();
    doc
      .fontSize(10)
      .fillColor("#0f172a")
      .text(`[  ] ${line}`, { width: 499 });
    doc.moveDown(0.15);
  }

  doc.moveDown(1);
  doc
    .fontSize(10)
    .fillColor("#0f172a")
    .text("Declaration:", 48, doc.y, { underline: true });
  doc
    .fontSize(10)
    .fillColor("#0f172a")
    .text(
      "I have read (or had read to me in a language I understand) the above consent. I fully understand its contents and I freely and voluntarily give my consent to the proposed dental treatment.",
      { width: 499, align: "justify" },
    );

  doc.moveDown(2);
  doc.fontSize(9).fillColor("#64748b").text(`Date: ${formatDate(new Date())}`, 48);
  signatureBlock(doc, "Patient / Guardian signature", "Attending dentist");
  signatureBlock(doc, "Witness (name & signature)", "Translator / relationship (if any)");

  drawFooter(doc, "Consent form — keep one copy in patient file.");
  doc.end();
  return promise;
}

/* -------------------------------------------------------------------------- */
/* PDF 5 — Orthodontic Treatment Record (DP + 9 adjustment satırı)            */
/* -------------------------------------------------------------------------- */

export async function generateOrthodonticRecordPdf(
  clinicId: string,
  patientId: string,
): Promise<Buffer> {
  const clinic = await fetchClinicHeader(clinicId);
  const p = await loadPatientFull(clinicId, patientId);

  const { doc, promise } = buildDoc();
  drawHeader(doc, clinic, "Orthodontic Treatment Record");

  sectionTitle(doc, "Patient");
  const fullName = [p.firstName, p.middleName, p.lastName].filter(Boolean).join(" ");
  twoColGrid(doc, [
    ["Full name", fullName],
    ["Date of birth", formatDate(p.birthDate)],
    ["Age", ageFromBirthDate(p.birthDate)],
    ["Gender", p.gender ?? ""],
    ["Phone", p.phone],
    ["Address", [p.address, p.city, p.province].filter(Boolean).join(", ")],
    ["Occupation", p.occupation ?? ""],
    ["Referred by", p.referralSource ?? ""],
  ]);

  sectionTitle(doc, "Diagnosis & treatment plan");
  const planRows: Array<[string, string]> = [
    ["Chief complaint", "______________________________________________"],
    ["Clinical findings", "______________________________________________"],
    ["Skeletal classification", "[ ] Class I   [ ] Class II   [ ] Class III"],
    ["Molar relation", "R: ____    L: ____"],
    ["Canine relation", "R: ____    L: ____"],
    ["Overjet (mm)", "______"],
    ["Overbite (mm)", "______"],
    ["Crowding", "Upper: ____ mm   Lower: ____ mm"],
    ["Treatment objectives", "______________________________________________"],
    ["Appliance", "[ ] Metal brackets  [ ] Ceramic  [ ] Self-ligating  [ ] Aligners"],
    ["Estimated duration", "______ months"],
    ["Total fee", money(0)],
    ["Retention plan", "______________________________________________"],
    ["Missed-visit policy discussed", "[ ] Yes   [ ] No"],
  ];
  twoColGrid(doc, planRows);

  sectionTitle(doc, "Adjustment log");
  const col = {
    n: 48,
    date: 80,
    wire: 150,
    force: 230,
    done: 310,
    next: 420,
    sig: 490,
  };
  const oHdrY = doc.y;
  doc.fontSize(8).fillColor("#64748b");
  doc.text("#", col.n, oHdrY);
  doc.text("DATE", col.date, oHdrY);
  doc.text("WIRE/ARCH", col.wire, oHdrY, { width: 72 });
  doc.text("FORCE/AUX.", col.force, oHdrY, { width: 72 });
  doc.text("WORK DONE", col.done, oHdrY, { width: 100 });
  doc.text("NEXT VISIT", col.next, oHdrY, { width: 62 });
  doc.text("SIG.", col.sig, oHdrY, { width: 52, align: "right" });
  doc.y = oHdrY + 11;
  doc.strokeColor("#cbd5e1").moveTo(48, doc.y).lineTo(547, doc.y).stroke();
  doc.moveDown(0.35);

  for (let i = 1; i <= 12; i++) {
    if (doc.y > 770) doc.addPage();
    const y = doc.y;
    doc.fontSize(10).fillColor("#0f172a").text(String(i), col.n, y, { width: 25 });
    doc
      .strokeColor("#e2e8f0")
      .lineWidth(0.4)
      .moveTo(48, y + 24)
      .lineTo(547, y + 24)
      .stroke();
    doc.moveDown(1.4);
  }

  sectionTitle(doc, "Notes & compliance");
  doc
    .fontSize(10)
    .fillColor("#0f172a")
    .text("Oral hygiene / elastic wear / breakages / patient concerns:", { width: 499 });
  for (let i = 0; i < 4; i++) {
    if (doc.y > 770) doc.addPage();
    const y = doc.y + 2;
    doc.strokeColor("#e2e8f0").lineWidth(0.4).moveTo(48, y + 14).lineTo(547, y + 14).stroke();
    doc.moveDown(1.2);
  }

  signatureBlock(doc, "Patient signature", "Orthodontist");
  drawFooter(doc, "Orthodontic treatment record — v1");
  doc.end();
  return promise;
}
