import { PerioSiteCode } from "@prisma/client";
import PDFDocument from "pdfkit";

import { prisma } from "../lib/prisma.js";

import { applyPdfUnicodeFont } from "./pdfKitUnicodeFont.js";

type Doc = PDFKit.PDFDocument;

const SITE_ORDER: PerioSiteCode[] = [
  PerioSiteCode.DB,
  PerioSiteCode.B,
  PerioSiteCode.MB,
  PerioSiteCode.ML,
  PerioSiteCode.L,
  PerioSiteCode.DL,
];

interface ClinicHeader {
  name: string;
  address: string | null;
  city: string | null;
  phone: string | null;
}

async function fetchClinicHeader(clinicId: string): Promise<ClinicHeader> {
  const c = await prisma.clinic.findUnique({
    where: { id: clinicId },
    select: { name: true, address: true, city: true, phone: true },
  });
  return {
    name: c?.name ?? "DentEase PH",
    address: c?.address ?? null,
    city: c?.city ?? null,
    phone: c?.phone ?? null,
  };
}

function formatDate(d: Date | null | undefined): string {
  if (!d) return "—";
  return new Date(d).toLocaleDateString("en-PH", {
    timeZone: "Asia/Manila",
    year: "numeric",
    month: "short",
    day: "2-digit",
  });
}

function drawHeader(doc: Doc, clinic: ClinicHeader, title: string): void {
  doc.fillColor("#0f172a").fontSize(18).text(clinic.name, 48, 48);
  doc
    .fillColor("#64748b")
    .fontSize(9)
    .text([clinic.address, clinic.city].filter(Boolean).join(", "), 48, 72);
  if (clinic.phone) doc.text(`Tel: ${clinic.phone}`, 48, 84);

  doc
    .fillColor("#7c3aed")
    .fontSize(13)
    .text(title, 48, 106, { align: "right", width: 499 });

  doc
    .strokeColor("#7c3aed")
    .lineWidth(2)
    .moveTo(48, 128)
    .lineTo(547, 128)
    .stroke();

  doc.y = 140;
  doc.x = 48;
}

function drawFooter(doc: Doc): void {
  const pages = doc.bufferedPageRange();
  for (let i = 0; i < pages.count; i++) {
    doc.switchToPage(i);
    doc
      .strokeColor("#cbd5e1")
      .lineWidth(0.5)
      .moveTo(48, 788)
      .lineTo(547, 788)
      .stroke();
    doc
      .fontSize(8)
      .fillColor("#94a3b8")
      .text(
        `Periodontal examination — Generated by DentEase PH   |   Page ${i + 1} / ${pages.count}`,
        48,
        794,
        { align: "center", width: 499 },
      );
  }
}

function buildDoc(): { doc: Doc; promise: Promise<Buffer> } {
  const doc = new PDFDocument({ size: "A4", margin: 48, bufferPages: true, layout: "portrait" });
  applyPdfUnicodeFont(doc);
  const chunks: Buffer[] = [];
  doc.on("data", (c: Buffer) => chunks.push(c));
  const promise = new Promise<Buffer>((resolve, reject) => {
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);
  });
  return { doc, promise };
}

type Exam = Awaited<ReturnType<typeof loadExam>>;

async function loadExam(clinicId: string, examId: string) {
  const exam = await prisma.perioExam.findFirst({
    where: { id: examId, clinicId },
    include: {
      patient: {
        select: {
          firstName: true,
          middleName: true,
          lastName: true,
          birthDate: true,
          gender: true,
          phone: true,
        },
      },
      examinedBy: { select: { firstName: true, lastName: true } },
      teeth: {
        orderBy: { toothNumber: "asc" },
        include: { sites: true },
      },
    },
  });
  if (!exam) throw new Error("Perio exam not found");
  return exam;
}

/**
 * Verilen diş numarası için site dizisini (6 elemanlı) sabit sıraya getirir.
 * Eksik siteler null olarak gelir.
 */
function orderedSites(
  sites: Exam["teeth"][number]["sites"],
): Array<Exam["teeth"][number]["sites"][number] | null> {
  return SITE_ORDER.map(
    (code) => sites.find((s) => s.siteCode === code) ?? null,
  );
}

/**
 * Tek çene için (üst veya alt) kompakt tablo çizer.
 * Kolonlar: diş numarası, bukkal 3 site (PD), lingual 3 site (PD), BOP sayısı, mobility, furcation.
 */
function drawArchTable(
  doc: Doc,
  teeth: Exam["teeth"],
  toothRange: number[],
  title: string,
): void {
  if (doc.y > 720) doc.addPage();

  doc.fillColor("#0f172a").fontSize(11).text(title, { underline: false });
  doc.moveDown(0.3);

  const startX = 48;
  const colWidths = {
    tooth: 32,
    site: 22, // 6 siteler
    bop: 28,
    mob: 32,
    fur: 32,
    cal: 34,
  };
  const rowH = 16;
  let y = doc.y;

  // Başlık satırı
  doc.fillColor("#475569").fontSize(8);
  let x = startX;
  doc.text("#", x, y, { width: colWidths.tooth, align: "center" });
  x += colWidths.tooth;
  ["DB", "B", "MB", "ML", "L", "DL"].forEach((label) => {
    doc.text(label, x, y, { width: colWidths.site, align: "center" });
    x += colWidths.site;
  });
  doc.text("BOP", x, y, { width: colWidths.bop, align: "center" });
  x += colWidths.bop;
  doc.text("Mob.", x, y, { width: colWidths.mob, align: "center" });
  x += colWidths.mob;
  doc.text("Furc.", x, y, { width: colWidths.fur, align: "center" });
  x += colWidths.fur;
  doc.text("CAL max", x, y, { width: colWidths.cal, align: "center" });

  y += rowH - 2;
  doc
    .strokeColor("#cbd5e1")
    .lineWidth(0.5)
    .moveTo(startX, y)
    .lineTo(startX + colWidths.tooth + colWidths.site * 6 + colWidths.bop + colWidths.mob + colWidths.fur + colWidths.cal, y)
    .stroke();
  y += 2;

  // Satırlar
  doc.fontSize(9);
  for (const tn of toothRange) {
    if (y > 760) {
      doc.addPage();
      y = 60;
    }

    const tooth = teeth.find((t) => t.toothNumber === tn);
    x = startX;

    doc.fillColor("#0f172a").text(String(tn), x, y, { width: colWidths.tooth, align: "center" });
    x += colWidths.tooth;

    if (!tooth || tooth.missing) {
      doc.fillColor("#94a3b8");
      doc.text("— missing —", x, y, {
        width: colWidths.site * 6,
        align: "center",
      });
      y += rowH;
      continue;
    }

    const sites = orderedSites(tooth.sites);
    let bleedCount = 0;
    let maxCal = 0;

    sites.forEach((s) => {
      if (!s) {
        doc.fillColor("#94a3b8").text("–", x, y, { width: colWidths.site, align: "center" });
      } else {
        const cal = s.pocketDepth + s.recession;
        if (cal > maxCal) maxCal = cal;
        if (s.bleeding) bleedCount++;
        const isDeep = s.pocketDepth >= 4;
        const isVeryDeep = s.pocketDepth >= 6;
        doc.fillColor(isVeryDeep ? "#991b1b" : isDeep ? "#dc2626" : "#0f172a");
        doc.text(
          String(s.pocketDepth) + (s.bleeding ? "•" : ""),
          x,
          y,
          { width: colWidths.site, align: "center" },
        );
      }
      x += colWidths.site;
    });

    doc.fillColor(bleedCount > 0 ? "#dc2626" : "#475569");
    doc.text(`${bleedCount}/6`, x, y, { width: colWidths.bop, align: "center" });
    x += colWidths.bop;

    doc.fillColor("#0f172a");
    doc.text(tooth.mobility != null ? String(tooth.mobility) : "–", x, y, {
      width: colWidths.mob,
      align: "center",
    });
    x += colWidths.mob;

    doc.text(tooth.furcation != null ? String(tooth.furcation) : "–", x, y, {
      width: colWidths.fur,
      align: "center",
    });
    x += colWidths.fur;

    doc.fillColor(maxCal >= 5 ? "#dc2626" : "#0f172a");
    doc.text(`${maxCal} mm`, x, y, { width: colWidths.cal, align: "center" });

    y += rowH;
  }

  doc.y = y + 6;
  doc.x = startX;
}

export async function generatePerioExamPdf(
  clinicId: string,
  examId: string,
): Promise<{ buffer: Buffer; filename: string }> {
  const clinic = await fetchClinicHeader(clinicId);
  const exam = await loadExam(clinicId, examId);
  const { doc, promise } = buildDoc();

  drawHeader(doc, clinic, "Periodontal Examination");

  // Hasta & muayene meta alanı
  const fullName = [exam.patient.firstName, exam.patient.middleName, exam.patient.lastName]
    .filter(Boolean)
    .join(" ");

  doc.fillColor("#0f172a").fontSize(11);
  doc.text(`Patient: ${fullName}`, 48, doc.y);
  doc.text(`Phone: ${exam.patient.phone ?? "—"}   •   Gender: ${exam.patient.gender ?? "—"}   •   DOB: ${formatDate(exam.patient.birthDate)}`);
  doc.moveDown(0.3);
  doc.text(
    `Exam date: ${formatDate(exam.examDate)}   •   Examined by: Dr. ${exam.examinedBy.firstName} ${exam.examinedBy.lastName}`,
  );
  doc.moveDown(0.6);

  // Özet kartlar
  const bop = exam.bopPercent ? Number(exam.bopPercent).toFixed(1) : "0.0";
  const plaque = exam.plaquePercent ? Number(exam.plaquePercent).toFixed(1) : "0.0";

  const activeTeeth = exam.teeth.filter((t) => !t.missing);
  let deep = 0;
  let veryDeep = 0;
  let sitesTotal = 0;
  activeTeeth.forEach((t) =>
    t.sites.forEach((s) => {
      sitesTotal++;
      if (s.pocketDepth >= 4) deep++;
      if (s.pocketDepth >= 6) veryDeep++;
    }),
  );

  const cardY = doc.y;
  const cards = [
    { label: "Bleeding on probing", value: `${bop}%`, color: Number(bop) > 20 ? "#dc2626" : "#10b981" },
    { label: "Plaque index", value: `${plaque}%`, color: Number(plaque) > 20 ? "#eab308" : "#10b981" },
    { label: "Pockets ≥ 4mm", value: `${deep} / ${sitesTotal}`, color: deep > 0 ? "#dc2626" : "#10b981" },
    { label: "Pockets ≥ 6mm", value: `${veryDeep}`, color: veryDeep > 0 ? "#991b1b" : "#10b981" },
  ];
  const cardW = (499 - 3 * 6) / 4;
  cards.forEach((c, i) => {
    const x = 48 + i * (cardW + 6);
    doc.roundedRect(x, cardY, cardW, 50, 4).fillAndStroke("#f8fafc", "#e2e8f0");
    doc.fillColor("#64748b").fontSize(8).text(c.label, x + 8, cardY + 8, { width: cardW - 16 });
    doc.fillColor(c.color).fontSize(16).text(c.value, x + 8, cardY + 24, { width: cardW - 16 });
  });
  doc.y = cardY + 62;
  doc.x = 48;

  // Üst çene (1-16) ve alt çene (17-32) için tablolar
  drawArchTable(
    doc,
    exam.teeth,
    Array.from({ length: 16 }, (_, i) => i + 1),
    "Maxilla (Upper arch) — Teeth 1 to 16",
  );

  drawArchTable(
    doc,
    exam.teeth,
    Array.from({ length: 16 }, (_, i) => i + 17),
    "Mandible (Lower arch) — Teeth 17 to 32",
  );

  // Açıklama
  if (doc.y > 720) doc.addPage();
  doc.moveDown(0.5);
  doc.fillColor("#64748b").fontSize(8);
  doc.text(
    "Legend: PD values in mm. • = bleeding on probing. PD ≥ 4 shown in red, PD ≥ 6 in dark red. CAL = PD + Recession.",
    { width: 499 },
  );
  doc.text(
    "Mobility (Miller): 0 = normal, 1 = < 1mm, 2 = 1-2mm, 3 = > 2mm or vertical. Furcation (Glickman): 0 = none, 1 = beginning, 2 = partial, 3 = through-and-through.",
    { width: 499 },
  );

  // Notlar
  if (exam.notes) {
    doc.moveDown(0.8);
    doc.fillColor("#0f172a").fontSize(11).text("Clinical notes");
    doc.moveDown(0.2);
    doc.fillColor("#334155").fontSize(10).text(exam.notes, { width: 499 });
  }

  // İmza satırı
  if (doc.y > 720) doc.addPage();
  doc.moveDown(3);
  const sigY = doc.y;
  doc.strokeColor("#0f172a").lineWidth(0.7);
  doc.moveTo(48, sigY).lineTo(280, sigY).stroke();
  doc.moveTo(320, sigY).lineTo(547, sigY).stroke();
  doc.fillColor("#475569").fontSize(9);
  doc.text(
    `Dr. ${exam.examinedBy.firstName} ${exam.examinedBy.lastName} — Examining dentist`,
    48,
    sigY + 4,
    { width: 232, align: "center" },
  );
  doc.text("Patient signature", 320, sigY + 4, { width: 227, align: "center" });

  drawFooter(doc);
  doc.end();

  const buffer = await promise;
  const filename = `perio-exam-${formatDate(exam.examDate).replace(/[^0-9A-Za-z]+/g, "")}-${exam.id}.pdf`;
  return { buffer, filename };
}
